### PR TITLE
Tasks block 1

### PR DESCRIPTION
**Pull request by ashish173**
Work for new specifications given by @viniromualdo in #106 

Resolves #115

### CODE REVIEW

**Comment by koyan** [comment]
@ashish173 does this have markup changes? I see the index.html being changed in much more places than the Tasks Block would justify. Could you minimise the changes to only the relevant parts please?

**Comment by ashish173** [comment]
@koyan as of now there are no markup changes for the tasks block; these are just changes for the tab size which is set to 2 spaces in my editor and in master it was set to 2 tabs(8 spaces long), I'll talk to the team about it.

**Comment by koyan** [comment]
If there are no changes, please remove this file from the commit, and only include files where you have actually done changes.

**Comment by ashish173** [comment]
@koyan I just want to follow the standard which the team agreed on, and this file was not as per that rule for indentation so I made the change.

We have set the standard rule in `.editorconfig` file.

```
[*]
end_of_line = lf
indent_style = space
indent_size = 2
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
```

Most `.html` files in the repo are following this rule except for `issues.html` has 4 tabs, `explore.html` has 2 tabs indentation. They should be changed as well if we have to stick to the above rule.

**Comment by koyan** [comment]
Then do those changes in a different PR, related to following the standard. You should not mix the contexts. If this PR is for the Tasks Block, only include Tasks Block related changes in it please.

**Comment by ashish173** [comment]
@koyan okay, I'll push a commit which reverts this change in this branch and send a new PR. Thanks for your feedback!

**Comment by Kluny** [comment]
Broke @viniromualdo's spec down into this task list:

√ S + M screens: works like an accordion, so default starts with the first task expanded,

√ all rest collapsed.
√ Tapping on collapsed task causes it to expand and reveal inner paragraph and Call to action (btn, img...).
√ The previously expanded tasks remain expanded unless intentionally collapsed back.

TODO: Style should change accordingly as in the designs.
    (change "take action" button to "share" and orange to yellow)

TODO: First task number should be bigger than the others

√ L + XL screens: all content is always visible in all tasks.

TODO: Hovering over another task causes it to go from faded state (50% opacity) to 100% opacity, while all other tasks get faded. (Right now first task stays opaque)

√ By default the first task has a 100% opacity (even when not hovered).
√ Mouse cursor should be normal everywhere in the task area EXCEPT when over a CTA (btn, img...).
√ In this last case cursor should be a hand.
√ There are no longer click states, in other words, clicking on a task doesn't change its color.

I'm still not sure the hover/opacity behaviour is working as it should. Technically I think it meets the spec, but maybe @viniromualdo could look at how it is now and tell me whether it falls short. Should the "active" state be persistent after user mouses off a step?

**Pull request closed without merging**
