### PR TITLE
Comments block

### PR DESCRIPTION
**Pull request by mikeselander**
Cleaning up and making the comment block markup semantic.

Note: I'm using the `page-section` classes from #53 so the overall block-level spacing is off, but will align properly once both PRs are in master.

### CODE REVIEW

**Comment by Kluny** [comment]
Please resolve the conflicts. Or, if you trust me and you want to give me something to do, I can probably resolve them for you.

**Comment by mikeselander** [comment]
@Kluny were there any issues or is this approved?

**Comment by mikeselander** [comment]
Approved in person by @rianrietveld

**Comment by Kluny** [comment]
Looks like you merged the branch I thought was conflicting first, so no problem!

**Pull request merged**
