### PR TITLE
Remove Built Style Files

### LINKED ISSUE #32: Maybe Remove Built Files
**Question for all:**
Are the static, built CSS & JS files used, beyond styling the local site for testing?

We have several built files in the repo - this is generally considered bad practice as merge conflicts are more likely, and keeping track of the source files only and building files as a part of the deploy process is cleaner. Additionally, it mucks up diff rates and means that git always thinks that there is always changes on even the smallest modification.

However, I don't want to accidentally mess up an existing deploy process or workflow if there is one.

### PR DESCRIPTION
**Pull request by mikeselander**
Removing these files from the master branch to clean up our diffs and resolve #32

### CODE REVIEW

**Comment by Kluny** [comment]
Looks ok to me, could you just indicate which built files these ones are redundant with?

**Comment by mikeselander** [comment]
@Kluny these aren't redundant files, it's just not great practice to store the built files in the repository itself so we're removing them from the `master` branch and are only storing a single set of built CSS files in the `gh_pages` branch instead.

**Comment by ashish173** [comment]
LGTM 👍

**Comment by Kluny** [comment]
@mikeselander understood!

**Pull request merged**
