### PR TITLE
Fixes to language dropdown

### PR DESCRIPTION
**Pull request by pdewouters**
I noticed when you expand the menu on mobile and then click the dropdown, it closes the menu. this is caused by the Javascript in `header.js`
I'd recommend adding a close icon to the expanded menu instead.

### CODE REVIEW

**Comment by kadamwhite** [comment]
This is likely to be superseded by cleanup work I’m doing on the header, but leaving open for now

**Comment by pdewouters** [comment]
@kadamwhite just FYI -  I fixed the HTML for the dropdown, also fixed the styles for the expanded menu
lang-portrait
main_nav_xl
main_nav_m 1
main_nav_l 1
main_nav_s

**Comment by kadamwhite** [comment]
Thanks for that! I didn’t see styling for the mobile language menu, is This based on something from design or was it the best available solution?

**Comment by pdewouters** [comment]
this was provided by the designers yes - I assume the last image is for mobile

**Comment by mikeselander** [comment]
This looks to be superseded by #110. Closing.

**Pull request closed without merging**
