### PR TITLE
Add default page template

### PR DESCRIPTION
**Pull request by comzeradd**
This implements a very simple default page template (issue [PLANET-1515](https://jira.greenpeace.org/browse/PLANET-1515)).

I did a small css hack to make sure only the first container has padding, since we can't predict what other blocks a page may include.

### CODE REVIEW

**Comment by koyan** [comment]
Oh carp, the "has markup changes" in this case means "a full page". 
May I suggest one of the following: 
a) You commit first a "current page" so that we can easily find out which are the changes
or
b) You do the markup changes in the twig file?

**Comment by comzeradd** [comment]
I do. I just opened a PR with changes at greenpeace/planet4-master-theme#211

It's very few changesm but we didn't have a vanilla page template on presentation layer at all.

**Comment by ashish173** [comment]
@comzeradd Just wondering this css is going to be applied to the first container in all the cases right? is that a desirable behaviour ?

**Comment by comzeradd** [comment]
Yes, the intention is to have the paddings only to the container that's right after `page-template`. See [here](https://github.com/greenpeace/planet4-presentation-layer/pull/216/files#diff-3b17ae963ca4cd3b8e345184a1725110R242).

Any other container that's from a block (eg. articles-listing) and it's one more level down the markup tree should have zero paddings. Otherwise these blocks would end up with double paddings and would look weird.

**Comment by ashish173** [comment]
okay, makes sense!

**Pull request merged**
